/* ============================================================
   LANGUE : NÉERLANDAIS
   Les clés manquantes ici seront prises depuis lang_fr.js
   ============================================================ */
var LANG_DATA = {
  btnSave:        'Opslaan',
  btnClearAll:    'Alles wissen',
  btnCancel:      'Annuleren',
  btnOk:          'Bevestigen',
  lblVehicle:     'Voertuigmodel',
  lblDamages:     'Geplaatste schade',
  lblTypes:       'Types (max 5)',
  lblGravity:     'Ernst',
  lblNote:        'Opmerking',
  sevLow:         'Licht',
  sevMedium:      'Gemiddeld',
  sevHigh:        'Ernstig',
  confirmDelete:  'Alle schade wissen?',
  noType:         'Selecteer minstens één type',
  maxTypes:       'Maximaal 5 types',
  msgLoaded:      '%n schade(s) geladen',
  titlePopup:     'Schade #',
  hint:           'Klik op carrosserie = schade plaatsen · slepen = draaien · scroll = zoom',
  loading:        'Initialisatie…',
  loadingModel:   'Laden ',
  waitModel:      'Wachten op model van WinDev…',
  decoding:       'Model decoderen…',
  errParse:       'Parseerfout model (zie console)',
  errLoad:        'Laadfout — serveer de map via HTTP',
  errBase64:      'Base64-fout (zie console)',
  memoPlaceholder:'Optionele opmerking…',
  dmgRust:        'Roest',
  dmgDent:        'Deuk',
  dmgHail:        'Hagel',
  dmgBirdpoop:    'Vogelpoep',
  dmgScratch:     'Kras',
  dmgCrack:       'Barst voorruit',
  dmgStar:        'Ster voorruit',
  btnReport2D:    '2D-rapport',
  reportTitle:    'Schaderapport',
  reportGenerated:'Gegenereerd op',
  reportCarstock: 'Voertuig',
  reportJob:      'Werkorder',
  reportModel:    'Model',
  reportPrint:    'Afdrukken',
  reportClose:    'Sluiten',
  reportRefresh:  'Vernieuwen',
  reportSummary:  'Schadeoverzicht',
  reportNoDamage: 'Geen schade geregistreerd',
  reportTypes:    'Type(s)',
  reportSeverity: 'Ernst',
  reportMemo:     'Opmerking',
  reportPosition: 'Positie',
  reportMarkers:  'zichtbare schade(s)',
  reportNotReady: 'Het 3D-model is nog niet klaar.',
  viewFront:      'Voorkant',
  viewRear:       'Achterkant',
  viewLeft:       'Linkerkant',
  viewRight:      'Rechterkant',
  viewTop:        'Bovenaanzicht'
};
