/* ============================================================
   LANGUE : ENGLISH
   Missing keys here will fallback to lang_fr.js
   ============================================================ */
var LANG_DATA = {
  btnSave:        'Save',
  btnClearAll:    'Clear all',
  btnCancel:      'Cancel',
  btnOk:          'Confirm',
  lblVehicle:     'Vehicle model',
  lblDamages:     'Placed damages',
  lblTypes:       'Types (max 5)',
  lblGravity:     'Severity',
  lblNote:        'Note',
  sevLow:         'Low',
  sevMedium:      'Medium',
  sevHigh:        'High',
  confirmDelete:  'Clear all damages?',
  noType:         'Select at least one type',
  maxTypes:       'Maximum 5 types',
  msgLoaded:      '%n damage(s) loaded',
  titlePopup:     'Damage #',
  hint:           'Click body = place damage · drag = rotate · scroll = zoom',
  loading:        'Initializing…',
  loadingModel:   'Loading ',
  waitModel:      'Waiting for model from WinDev…',
  decoding:       'Decoding model…',
  errParse:       'Model parse error (see console)',
  errLoad:        'Load error — serve folder via HTTP',
  errBase64:      'Base64 error (see console)',
  memoPlaceholder:'Optional comment…',
  dmgRust:        'Rust',
  dmgDent:        'Dent',
  dmgHail:        'Hail',
  dmgBirdpoop:    'Birdpoop',
  dmgScratch:     'Scratch',
  dmgCrack:       'Windshield crack',
  dmgStar:        'Windshield star',
  btnReport2D:    '2D report',
  reportTitle:    'Damage report',
  reportGenerated:'Generated on',
  reportCarstock: 'Vehicle',
  reportJob:      'Job',
  reportModel:    'Model',
  reportPrint:    'Print',
  reportClose:    'Close',
  reportRefresh:  'Refresh',
  reportSummary:  'Damage summary',
  reportNoDamage: 'No damage recorded',
  reportTypes:    'Type(s)',
  reportSeverity: 'Severity',
  reportMemo:     'Memo',
  reportPosition: 'Position',
  reportMarkers:  'visible damage(s)',
  reportNotReady: 'The 3D model is not ready yet.',
  viewFront:      'Front',
  viewRear:       'Rear',
  viewLeft:       'Left side',
  viewRight:      'Right side',
  viewTop:        'Top'
};
